# Generated by Django 3.1.5 on 2021-03-28 17:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date du diagnostic')),
                ('cp', models.CharField(choices=[('0', 'Valeur: 0'), ('1', 'Valeur: 1'), ('2', 'Valeur: 2'), ('3', 'Valeur: 3')], default='1', help_text='(4 values)', max_length=13, verbose_name='Chest pain type')),
                ('trestbps', models.IntegerField(default=130, help_text='Resting blood pressure (in mm Hg on admission to the hospital)', verbose_name='Resting blood pressure')),
                ('chol', models.IntegerField(default=236, help_text='mg/dl', verbose_name='Serum cholestoral')),
                ('fbs', models.CharField(choices=[('1', '> 120 mg/dl'), ('0', '<= 120 mg/dl')], default='0', help_text='(fasting blood sugar > 120 mg/dl) (1 = true; 0 = false)', max_length=13, verbose_name='Fasting blood sugar')),
                ('restecg', models.CharField(choices=[('0', 'Valeur: 0'), ('1', 'Valeur: 1'), ('2', 'Valeur: 2')], default='0', help_text=' (values 0,1,2)', max_length=13, verbose_name='Resting electrocardiographic results')),
                ('thalach', models.IntegerField(default=174, verbose_name='Maximum heart rate achieved')),
                ('exang', models.CharField(choices=[('1', 'Yes'), ('0', 'NO')], default='0', help_text='exercise induced angina (1 = yes; 0 = no)', max_length=13, verbose_name='Exercise induced angina')),
                ('oldpeak', models.DecimalField(decimal_places=1, default=0.0, help_text='Oldpeak = ST depression induced by exercise relative to rest', max_digits=2, verbose_name='Oldpeak')),
                ('slope', models.CharField(choices=[('0', 'Valeur: 0'), ('1', 'Valeur: 1'), ('2', 'Valeur: 2')], default='1', help_text='The slope of the peak exercise ST segment', max_length=13, verbose_name='Slope')),
                ('ca', models.CharField(choices=[('0', 'Valeur: 0'), ('1', 'Valeur: 1'), ('2', 'Valeur: 2'), ('3', 'Valeur: 3')], default='1', help_text='Number of major vessels (0-3) colored by flourosopy', max_length=13, verbose_name='Number of major vessels')),
                ('thal', models.CharField(choices=[('1', 'Valeur: 1'), ('2', 'Valeur: 2'), ('3', 'Valeur: 3')], default='2', help_text='Thal: 3 = normal; 6 = fixed defect; 7 = reversable defect', max_length=13, verbose_name='Thal')),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('dateDeNaissance', models.DateField(default=django.utils.timezone.now, verbose_name='Date de naissance')),
                ('sex', models.CharField(blank=True, choices=[('0', 'M'), ('1', 'F')], default='0', help_text='(0 = male; 1 = female)', max_length=1, verbose_name='Sexe')),
                ('phone', models.CharField(default='', help_text='xxx xx xx xxxx', max_length=200, verbose_name='Téléphone')),
                ('addresse', models.CharField(help_text='Numero, Rue', max_length=200, null=True)),
                ('identifiantCin_Nif', models.CharField(max_length=200, null=True, verbose_name='Cin ou Nif')),
            ],
            options={
                'ordering': ['utilisateur'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('diagnostic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.diagnostic')),
                ('ordonnance', models.CharField(max_length=500)),
                ('notesImportantes', models.CharField(max_length=200, verbose_name='Notes importantes')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('Heure', models.TimeField()),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dossier')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
            },
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dossier'),
        ),
    ]
