# Generated by Django 3.1.5 on 2021-03-16 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossier',
            options={'ordering': ['utilisateur']},
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='informations',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='informations',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='informations',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='informations',
        ),
    ]
