# Generated by Django 3.1.4 on 2021-03-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='phone',
            field=models.CharField(default='', help_text='xxx xx xx xxxx', max_length=200, verbose_name='Téléphone'),
        ),
    ]
