# Generated by Django 3.1.4 on 2021-01-27 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='dossier',
            new_name='diagnostic',
        ),
    ]
