# Generated by Django 3.1.5 on 2021-01-31 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date du diagnostic'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='dateDeNaissance',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notesImportantes',
            field=models.CharField(max_length=200, verbose_name='Notes importantes'),
        ),
    ]
