# Generated by Django 3.1.4 on 2021-01-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='ca',
            field=models.CharField(choices=[('0', 'Valeur: 0'), ('1', 'Valeur: 1'), ('2', 'Valeur: 2'), ('3', 'Valeur: 3')], default='1', help_text='Number of major vessels (0-3) colored by flourosopy', max_length=13, verbose_name='Number of major vessels'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='slope',
            field=models.CharField(choices=[('0', 'Valeur: 0'), ('1', 'Valeur: 1'), ('2', 'Valeur: 2')], default='1', help_text='The slope of the peak exercise ST segment', max_length=13, verbose_name='Slope'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='thal',
            field=models.CharField(choices=[('1', 'Valeur: 1'), ('2', 'Valeur: 2'), ('3', 'Valeur: 3')], default='2', help_text='Thal: 3 = normal; 6 = fixed defect; 7 = reversable defect', max_length=13, verbose_name='Thal'),
        ),
    ]
