# Generated by Django 3.1.5 on 2021-03-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210328_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='Heure',
            field=models.TimeField(),
        ),
    ]
