# Generated by Django 3.1.5 on 2021-01-31 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210131_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'verbose_name': 'Rendez-vous', 'verbose_name_plural': 'Rendez-vous'},
        ),
    ]
