# Generated by Django 3.1.5 on 2021-01-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210128_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='restecg',
            field=models.CharField(choices=[('0', 'Valeur: 0'), ('1', 'Valeur: 1'), ('2', 'Valeur: 2')], default='0', help_text=' (values 0,1,2)', max_length=13, verbose_name='Resting electrocardiographic results'),
        ),
    ]
