# Generated by Django 3.1.4 on 2021-01-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210128_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='ca',
            field=models.CharField(default='', help_text='Number of major vessels (0-3) colored by flourosopy', max_length=13, verbose_name='Number of major vessels'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='chol',
            field=models.CharField(default='', help_text='mg/dl', max_length=13, verbose_name='Serum cholestoral'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='exang',
            field=models.CharField(default='', help_text='exercise induced angina (1 = yes; 0 = no)', max_length=13, verbose_name='Exercise induced angina'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='fbs',
            field=models.CharField(default='', help_text='(fasting blood sugar > 120 mg/dl) (1 = true; 0 = false)', max_length=13, verbose_name='Fasting blood sugar'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='oldpeak',
            field=models.CharField(default='', help_text='Oldpeak = ST depression induced by exercise relative to rest', max_length=13, verbose_name='Oldpeak'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='restecg',
            field=models.CharField(default='', help_text=' (values 0,1,2)', max_length=13, verbose_name='Resting electrocardiographic results'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='slope',
            field=models.CharField(default='', help_text='The slope of the peak exercise ST segment', max_length=13, verbose_name='Slope'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='thal',
            field=models.CharField(default='', help_text='Thal: 3 = normal; 6 = fixed defect; 7 = reversable defect', max_length=13, verbose_name='Thal'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='thalach',
            field=models.CharField(default='', max_length=13, verbose_name='Maximum heart rate achieved'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='trestbps',
            field=models.IntegerField(default=130, help_text='Resting blood pressure (in mm Hg on admission to the hospital)', verbose_name='Resting blood pressure'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='sex',
            field=models.CharField(blank=True, choices=[('0', 'M'), ('1', 'F')], default='0', help_text='(1 = male; 0 = female)', max_length=1, verbose_name='Sexe'),
        ),
    ]
