# Generated by Django 3.1.2 on 2021-01-02 15:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dia_mvc_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dossiers',
            new_name='Dossier',
        ),
    ]
